import { useState, useEffect, useRef } from 'react';
import { FileText, Scale, AlertTriangle, CreditCard, Shield } from 'lucide-react';
import Footer from './Footer-ai';
import Navbar from './Navbar-ai';

const TermsAndConditions = () => {
  const [isVisible, setIsVisible] = useState(false);
  const sectionRef = useRef<HTMLElement>(null);

  useEffect(() => {
    setIsVisible(true);
  }, []);

  return (
    <div className="min-h-screen">
      <Navbar />
      
      <section 
        ref={sectionRef}
        className="py-20 bg-gradient-to-b from-slate-50 to-white relative"
      >
        <div className="absolute inset-0 opacity-5">
          <div className="absolute inset-0" style={{
            backgroundImage: `url("data:image/svg+xml,%3Csvg width='40' height='40' viewBox='0 0 40 40' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='%23334155' fill-opacity='0.1'%3E%3Ccircle cx='20' cy='20' r='1'/%3E%3C/g%3E%3C/svg%3E")`
          }}></div>
        </div>

        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          {/* Professional Header */}
          <div className="text-center mb-12">
            <div className={`transform transition-all duration-1000 ${isVisible ? 'translate-y-0 opacity-100' : 'translate-y-10 opacity-0'}`}>
              <div className="inline-flex items-center px-4 py-2 bg-blue-50 text-blue-700 rounded-full text-sm font-semibold mb-4">
                <Scale className="w-4 h-4 mr-2" />
                Legal Agreement
              </div>
              <h1 className="text-4xl font-bold text-slate-900 mb-4">
                Terms and Conditions
              </h1>
            </div>
            <div className={`transform transition-all duration-1000 delay-200 ${isVisible ? 'translate-y-0 opacity-100' : 'translate-y-10 opacity-0'}`}>
              <p className="text-lg text-slate-600">
                Last Updated: June 13, 2025
              </p>
            </div>
          </div>

          {/* Razorpay UPI Compliance Notice */}
          <div className={`bg-blue-50 rounded-xl border border-blue-200 p-6 mb-8 transform transition-all duration-1000 delay-300 ${isVisible ? 'translate-y-0 opacity-100' : 'translate-y-10 opacity-0'}`}>
            <div className="flex items-start">
              <div className="flex-shrink-0 bg-blue-100 rounded-full p-2">
                <CreditCard className="h-5 w-5 text-blue-700" />
              </div>
              <div className="ml-3">
                <h3 className="text-sm font-medium text-blue-800">Razorpay UPI Payment Information</h3>
                <div className="mt-2 text-sm text-blue-700">
                  <p>Intruitia uses Razorpay as our authorized payment gateway for UPI and other online transactions. All transactions are processed securely and in compliance with RBI guidelines.</p>
                  <p className="mt-1">By using our services, you agree to the payment terms outlined in this document.</p>
                </div>
              </div>
            </div>
          </div>

          <div className={`bg-white rounded-xl shadow-sm border border-slate-200 p-8 mb-8 transform transition-all duration-1000 ${isVisible ? 'translate-y-0 opacity-100' : 'translate-y-10 opacity-0'}`}>
            <div className="space-y-8">
              <div>
                <h2 className="text-2xl font-bold text-slate-900 mb-4 flex items-center">
                  <FileText className="w-6 h-6 mr-2 text-blue-600" />
                  Introduction
                </h2>
                <p className="text-slate-600 leading-relaxed mb-4">
                  This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                </p>
                <p className="text-slate-600 leading-relaxed mb-4">
                  This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name https://www.intruitia.in/ ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').
                </p>
                <p className="text-slate-600 leading-relaxed mb-4">
                  The Platform is owned by Intruitia, a registered Micro Enterprise based in Hyderabad, India (UDYAM-TS-20-0135173), with its registered office at Flat No. 2-90/9/2/1, Jeevan Jyothi Nagar, Suraram Colony, Hyderabad, Telangana 500055, India (hereinafter referred to as 'Platform Owner', 'we', 'us', 'our').
                </p>
                <p className="text-slate-600 leading-relaxed">
                  ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold text-slate-900 mb-4">
                  Definitions
                </h2>
                <ul className="list-disc pl-6 space-y-2 text-slate-600">
                  <li><span className="font-semibold">"We," "Our," or "Us"</span> refers to Intruitia.</li>
                  <li><span className="font-semibold">"You" or "Your"</span> refers to the user or viewer of our website or client of our services.</li>
                  <li><span className="font-semibold">"Services"</span> refers to all services provided by Intruitia, including web development, content creation, and consulting services.</li>
                  <li><span className="font-semibold">"Website"</span> refers to intruitia.in and all associated content.</li>
                  <li><span className="font-semibold">"Platform"</span> refers to our Website, including the related mobile site and mobile application.</li>
                  <li><span className="font-semibold">"UPI"</span> refers to Unified Payments Interface, a real-time payment system developed by the National Payments Corporation of India.</li>
                  <li><span className="font-semibold">"Razorpay"</span> refers to our authorized payment gateway service provider for processing online payments, including UPI transactions.</li>
                </ul>
              </div>

              <div>
                <h2 className="text-2xl font-bold text-slate-900 mb-4">
                  General Terms
                </h2>
                <ul className="list-disc pl-6 space-y-2 text-slate-600 mb-4">
                  <li>Your use of the Platform and services and tools are governed by these Terms and Conditions as applicable to the Platform including the applicable policies which are incorporated herein by way of reference.</li>
                  <li>If you transact on the Platform, you shall be subject to the policies that are applicable to the Platform for such transaction.</li>
                  <li>By mere use of the Platform, you shall be contracting with the Platform Owner and these terms and conditions including the policies constitute your binding obligations with Platform Owner.</li>
                  <li>Any terms and conditions proposed by you which are in addition to or which conflict with these Terms are expressly rejected by the Platform Owner and shall be of no force or effect.</li>
                  <li>These Terms can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms to stay informed of updates.</li>
                  <li>To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.</li>
                  <li>For payments made via UPI through Razorpay, you agree to comply with all applicable guidelines of NPCI and RBI, and you confirm that you are authorized to use the UPI ID provided for payment.</li>
                  <li>You agree not to dispute UPI transactions without valid reasons and to report any payment discrepancies within 3 days of the transaction.</li>
                </ul>
                <p className="text-slate-600 leading-relaxed">
                  For the purpose of these Terms, wherever the context so requires 'you', 'your' or 'user' shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold text-slate-900 mb-4">
                  Services and Pricing
                </h2>
                <p className="text-slate-600 leading-relaxed mb-4">
                  We offer a range of digital services, including web development, content creation, and startup consulting. Detailed descriptions of our services and corresponding pricing are available upon request and will be provided in your service proposal or contract.
                </p>
                <p className="text-slate-600 leading-relaxed mb-4">
                  All prices are quoted in Indian Rupees (INR) unless otherwise stated. We reserve the right to change our pricing at any time; however, any price changes will not affect services for which you have already signed a contract.
                </p>
                <p className="text-slate-600 leading-relaxed">
                  The full scope of work, deliverables, timeline, and payment schedule will be detailed in a separate service agreement or proposal provided to you.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold text-slate-900 mb-4">
                  Payment Terms
                </h2>
                <p className="text-slate-600 leading-relaxed mb-4">
                  Payment terms will be specified in your service agreement or proposal. Typically, we require:
                </p>
                <ul className="list-disc pl-6 space-y-2 text-slate-600 mb-4">
                  <li>An initial deposit before commencing work</li>
                  <li>Milestone payments throughout the project</li>
                  <li>Final payment upon project completion</li>
                </ul>
                <p className="text-slate-600 leading-relaxed mb-4">
                  We accept payments through bank transfers, credit/debit cards, UPI, and digital payment platforms including Razorpay. All payments processed through Razorpay are subject to Razorpay's terms of service and privacy policy.
                </p>
                <p className="text-slate-600 leading-relaxed mb-4">
                  For UPI payments, transactions are processed in accordance with the National Payments Corporation of India (NPCI) guidelines. UPI payments are secure, and your UPI PIN is never stored or accessible by us.
                </p>
                <p className="text-slate-600 leading-relaxed mb-4">
                  When using UPI for payments:
                </p>
                <ul className="list-disc pl-6 space-y-2 text-slate-600 mb-4">
                  <li>You authorize Razorpay to debit the payment from your linked bank account.</li>
                  <li>You confirm that you are authorized to use the UPI ID provided for making payments.</li>
                  <li>UPI transactions are typically processed instantly, and service delivery will begin only after successful payment confirmation.</li>
                  <li>You must report any unauthorized transactions or discrepancies within 3 days of the transaction.</li>
                  <li>You agree to comply with all applicable UPI regulations and guidelines issued by NPCI and RBI.</li>
                  <li>You acknowledge that UPI transactions are final and cannot be cancelled once completed. For refunds, please refer to our Refund Policy.</li>
                </ul>
                <p className="text-slate-600 leading-relaxed">
                  Invoices are due upon receipt unless otherwise specified. Late payments may incur a late fee of 2% per month on the outstanding amount.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold text-slate-900 mb-4">
                  Intellectual Property Rights
                </h2>
                <p className="text-slate-600 leading-relaxed mb-4">
                  Upon full payment of all invoices related to your project, you will receive ownership rights to the final deliverables, except for:
                </p>
                <ul className="list-disc pl-6 space-y-2 text-slate-600 mb-4">
                  <li>Third-party materials that may be incorporated into the deliverables</li>
                  <li>Our proprietary tools, code libraries, or methodologies used to create the deliverables</li>
                  <li>Generic elements that are not unique to your project</li>
                </ul>
                <p className="text-slate-600 leading-relaxed">
                  We reserve the right to showcase your project in our portfolio unless you specifically request otherwise in writing.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold text-slate-900 mb-4">
                  Cancellation and Refund Policy
                </h2>
                <p className="text-slate-600 leading-relaxed mb-4">
                  Our cancellation and refund policy is as follows:
                </p>
                <ul className="list-disc pl-6 space-y-2 text-slate-600">
                  <li>Initial deposits are non-refundable as they cover initial consultations and project setup.</li>
                  <li>If you cancel a project after work has begun, you will be billed for all work completed up to the cancellation date.</li>
                  <li>For ongoing retainer services, cancellation requires a 30-day written notice.</li>
                  <li>All refunds, when applicable, will be processed within 5-7 business days through the original payment method.</li>
                  <li>For UPI payments, refunds will be sent to the same UPI ID used for the original transaction within 2-5 business days.</li>
                  <li>Once a refund is initiated, it cannot be canceled or reversed.</li>
                  <li>For detailed information on refunds and cancellations, including UPI payment refunds, please refer to our <a href="/refund-policy" className="text-blue-600 hover:underline">Refund Policy</a>.</li>
                  <li>For information on how we handle your payment data, please see our <a href="/privacy-policy" className="text-blue-600 hover:underline">Privacy Policy</a>.</li>
                </ul>
              </div>

              <div>
                <h2 className="text-2xl font-bold text-slate-900 mb-4 flex items-center">
                  <AlertTriangle className="w-6 h-6 mr-2 text-amber-500" />
                  Limitation of Liability
                </h2>
                <p className="text-slate-600 leading-relaxed">
                  To the maximum extent permitted by law, Intruitia shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenue, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from (a) your use or inability to use the services; (b) any unauthorized access to or use of our servers and/or any personal information stored therein; (c) any interruption or cessation of transmission to or from our services; (d) any bugs, viruses, trojan horses, or the like that may be transmitted to or through our services by any third party.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold text-slate-900 mb-4">
                  Governing Law
                </h2>
                <p className="text-slate-600 leading-relaxed">
                  These Terms shall be governed and construed in accordance with the laws of India, without regard to its conflict of law provisions. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the courts in Hyderabad, Telangana, India.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold text-slate-900 mb-4">
                  Changes to Terms
                </h2>
                <p className="text-slate-600 leading-relaxed">
                  We reserve the right to modify or replace these Terms at any time. If a revision is material, we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold text-slate-900 mb-4 flex items-center">
                  <FileText className="w-6 h-6 mr-2 text-blue-600" />
                  Contact Us
                </h2>
                <p className="text-slate-600 leading-relaxed mb-4">
                  If you have any questions about these Terms, please contact us:
                </p>
                <div className="bg-slate-50 p-6 rounded-lg border border-slate-200">
                  <p className="font-semibold text-slate-900 mb-1">Intruitia</p>
                  <p className="text-slate-600">Owner: Majji Pradeep Kumar</p>
                  <p className="text-slate-600">Email: support@intruitia.in</p>
                  <p className="text-slate-600">Phone: +91 8184889557</p>
                  <p className="text-slate-600">Address: Flat No. 2-90/9/2/1, Jeevan Jyothi Nagar, Suraram Colony, Hyderabad, Telangana 500055, India</p>
                </div>
              </div>

              <div>
                <h2 className="text-2xl font-bold text-slate-900 mb-4 flex items-center">
                  <Scale className="w-6 h-6 mr-2 text-violet-600" />
                  Dispute Resolution
                </h2>
                <p className="text-slate-600 leading-relaxed mb-4">
                  If you have any issues with our services or payment processes, please contact us first to resolve the matter amicably:
                </p>
                <ul className="list-disc pl-6 space-y-2 text-slate-600 mb-4">
                  <li>For payment disputes, including UPI transactions, please email us at support@intruitia.in with your transaction ID and details of the issue.</li>
                  <li>We aim to acknowledge all complaints within 24 hours and resolve them within 7 business days.</li>
                  <li>For UPI-related disputes, we follow the dispute resolution process outlined by NPCI and RBI guidelines.</li>
                  <li>In case of any discrepancy in payment, please report within 3 days of transaction for prompt resolution.</li>
                </ul>
                <p className="text-slate-600 leading-relaxed">
                  If we cannot reach an amicable resolution, the dispute will be subject to the exclusive jurisdiction of the courts in Hyderabad, Telangana, India.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
      
      <Footer />
    </div>
  );
};

export default TermsAndConditions;
